import { GameDefinition } from '../types.js';

export const GAME_REGISTRY: GameDefinition[] = [
  {
    id: 1,
    slug: 'blackjack',
    name: 'Blackjack',
    displayName: 'Classic 21 Blackjack',
    description: 'Beat the dealer by getting hand closer to 21 without busting. Includes Hit, Stand, Double Down, Split, and Insurance.',
    category: 'CARDS',
    iconName: 'Spade',
    thumbnail: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=600&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=1200&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 5000,
    maxMultiplier: '2.5x (Blackjack pays 3:2)',
    configuredRtp: 99.50,
    houseEdge: '0.50%',
    minAllowedRtp: 95.0,
    maxAllowedRtp: 99.8,
    sortOrder: 1,
    featured: true,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Get a hand value closer to 21 than the dealer without exceeding 21',
      'Face cards count as 10, Aces count as 1 or 11',
      'Hit to take another card, Stand to hold your hand',
      'Double Down doubles your wager for exactly one additional card',
      'Split pairs into two independent active hands',
      'Natural Blackjack (Ace + 10-value) pays 3:2'
    ],
    history: 'Blackjack originated from the French card game Vingt-et-Un in the 1700s and became the most popular casino card game worldwide.',
    strategy: 'Utilize basic strategy charts: always split Aces and 8s, never split 10s or 5s, double down on 11 vs dealer low card.',
    version: 1
  },
  {
    id: 2,
    slug: 'crash',
    name: 'Crash',
    displayName: 'Aviator Curve Crash',
    description: 'Watch the rocket ascent multiplier climb in real-time. Cash out before the rocket crashes to secure your multiplied winnings!',
    category: 'CRASH',
    iconName: 'TrendingUp',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 2500,
    maxMultiplier: '1000.00x',
    configuredRtp: 98.00,
    houseEdge: '2.00%',
    minAllowedRtp: 94.0,
    maxAllowedRtp: 99.0,
    sortOrder: 2,
    featured: true,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Place your wager before the rocket launch countdown concludes',
      'As the rocket flies, the multiplier increases exponentially',
      'Hit Cash Out before the random crash occurs to collect your stake × current multiplier',
      'If the rocket crashes before cashout, the wager is lost',
      'Set auto-cashout multipliers for automated risk management'
    ],
    history: 'Crash gambling originated in early cryptocurrency casinos and revolutionized live online multiplier prediction games.',
    strategy: 'Set sensible auto-cashout targets (1.2x - 2.0x) for consistent low-variance returns, or target high multipliers with smaller wagers.',
    version: 1
  },
  {
    id: 3,
    slug: 'mines',
    name: 'Mines',
    displayName: 'Neon Minesweeper',
    description: 'Uncover gems across the grid while dodging hidden mines. Every safe crystal increases your cashout multiplier exponentially.',
    category: 'CASUAL',
    iconName: 'Bomb',
    thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 5000,
    maxMultiplier: '10000.00x',
    configuredRtp: 98.50,
    houseEdge: '1.50%',
    minAllowedRtp: 94.0,
    maxAllowedRtp: 99.5,
    sortOrder: 3,
    featured: true,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Select grid size and the number of hidden mines (1 to N-1)',
      'Click covered tiles to reveal either a glowing Gem or an explosive Mine',
      'Each revealed gem increases your cumulative payout multiplier',
      'Cash out at any point to claim your accumulated win',
      'Hitting any mine detonates the board and ends the round'
    ],
    history: 'Inspired by the 1990s desktop puzzle Minesweeper, adapted with dynamic payout mathematics and verifiable probability.',
    strategy: 'Choosing 3-5 mines on a 5x5 grid offers optimal risk-to-reward balance. Cash out after 3-4 consecutive safe reveals.',
    version: 1
  },
  {
    id: 4,
    slug: 'slots',
    name: 'Slots',
    displayName: 'Neon 777 Video Slots',
    description: 'Classic 5-reel / 3-row slot machine with neon cherries, lucky sevens, diamonds, payline evaluation, and volatility selection.',
    category: 'SLOTS',
    iconName: 'Cherry',
    thumbnail: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 1000,
    maxMultiplier: '2500.00x',
    configuredRtp: 96.50,
    houseEdge: '3.50%',
    minAllowedRtp: 92.0,
    maxAllowedRtp: 98.5,
    sortOrder: 4,
    featured: true,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Choose bet stake and volatility mode (Low, Medium, High)',
      'Press Spin to rotate the reels with synchronized deceleration',
      'Match 3, 4, or 5 consecutive symbols along active paylines to trigger payouts',
      'Lucky Sevens and Diamonds trigger top-tier jackpot multipliers',
      'Auto-spin allows hands-free continuous entertainment'
    ],
    history: 'Invented in 1895 by Charles Fey as the mechanical Liberty Bell, transformed into high-definition digital reels.',
    strategy: 'Select Low volatility for extended steady sessions or High volatility when hunting high-multiplier symbol alignments.',
    version: 1
  },
  {
    id: 5,
    slug: 'dice',
    name: 'Dice',
    displayName: 'Quantum Dice',
    description: 'High-precision cryptographic dice roll. Adjust the win probability slider from 1% to 98% with instant transparent odds.',
    category: 'DICE',
    iconName: 'Dice5',
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 5000,
    maxMultiplier: '99.00x',
    configuredRtp: 99.00,
    houseEdge: '1.00%',
    minAllowedRtp: 95.0,
    maxAllowedRtp: 99.5,
    sortOrder: 5,
    featured: true,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Select Roll Over or Roll Under and adjust target threshold (1.00 to 98.00)',
      'The calculated win chance and exact payout multiplier update dynamically',
      'Roll the cryptographic die: if the outcome matches your condition, win instantly',
      'Deterministic provably fair SHA-256 seed verification on every roll'
    ],
    history: 'Dice games date back over 5,000 years to ancient Mesopotamia, modernized into high-frequency precision algorithms.',
    strategy: 'Roll Over 50.00 provides near 50/50 odds with 1.98x payout; lower target win chances yield huge payout multipliers.',
    version: 1
  },
  {
    id: 6,
    slug: 'coinflip',
    name: 'Coin Flip',
    displayName: 'Binary Coin Flip',
    description: 'Flip the two-sided golden coin for instant double payouts or build consecutive win streak multipliers.',
    category: 'CASUAL',
    iconName: 'Coins',
    thumbnail: 'https://images.unsplash.com/photo-1565372195458-9de0b320ef04?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 5000,
    maxMultiplier: '1.98x - 32.00x (Streak)',
    configuredRtp: 98.50,
    houseEdge: '1.50%',
    minAllowedRtp: 95.0,
    maxAllowedRtp: 99.5,
    sortOrder: 6,
    featured: false,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Select Heads (🦅) or Tails (👑)',
      'Flip the coin with 3D physics animation and audio synthesis',
      'Winning lands a 1.98x payout or allows rolling into a streak multiplier',
      'Streak mode doubles multipliers with each consecutive correct prediction'
    ],
    history: 'Known since Roman times as "heads or ships" (capita aut navia), the classic pure probability challenge.',
    strategy: 'Equal 50/50 probability on every independent flip. Avoid the gambler’s fallacy of chasing past patterns.',
    version: 1
  },
  {
    id: 7,
    slug: 'roulette',
    name: 'European Roulette',
    displayName: 'European Grand Roulette',
    description: 'Authentic 37-pocket single-zero European wheel with complete betting layout: Straight up, Splits, Streets, Corners, Red/Black, Even/Odd.',
    category: 'ROULETTE',
    iconName: 'Disc',
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 5000,
    maxMultiplier: '36.00x (Straight Up 35:1)',
    configuredRtp: 97.30,
    houseEdge: '2.70%',
    minAllowedRtp: 94.0,
    maxAllowedRtp: 98.5,
    sortOrder: 7,
    featured: true,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Place chips on individual numbers (0 to 36), dozens, columns, or outside 1:1 bets (Red/Black, Odd/Even, 1-18/19-36)',
      'The ivory ball spins around the 37-pocket European roulette wheel',
      'Straight up bets pay 35 to 1, Splits pay 17 to 1, Corners pay 8 to 1, Outside bets pay 1 to 1',
      'Single zero gives European roulette superior player odds compared to American double-zero'
    ],
    history: 'Invented in 18th century France by physicist Blaise Pascal and standardized in Monte Carlo casinos.',
    strategy: 'Outside even-money bets provide lowest volatility; combine outside bets with select corner coverage.',
    version: 1
  },
  {
    id: 8,
    slug: 'limbo',
    name: 'Limbo',
    displayName: 'Limbo Rocket',
    description: 'Set your target multiplier and watch the rocket blast off. If the random result meets or exceeds your target, collect the full multiplier!',
    category: 'CRASH',
    iconName: 'Rocket',
    thumbnail: 'https://images.unsplash.com/photo-1517976487507-5b3b4b45f47c?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 2500,
    maxMultiplier: '1000.00x',
    configuredRtp: 98.50,
    houseEdge: '1.50%',
    minAllowedRtp: 94.0,
    maxAllowedRtp: 99.0,
    sortOrder: 8,
    featured: false,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Enter your desired Target Multiplier (e.g. 1.5x up to 1000x)',
      'The win chance is automatically computed as (98.5 / Target)',
      'Launch the rocket: if the generated multiplier is >= Target Multiplier, win stake × Target Multiplier',
      'Instant resolution with cryptographic verification'
    ],
    history: 'Derived from instant-crash algorithms to give players instant single-click high-multiplier potential.',
    strategy: 'Lower targets (1.3x to 2.0x) maintain high win rates. Keep bankroll allocation under 2% per high-multiplier shot.',
    version: 1
  },
  {
    id: 9,
    slug: 'hilo',
    name: 'Hi-Lo',
    displayName: 'Hi-Lo Card Ladder',
    description: 'Predict whether the next card will be Higher, Lower, or Same. Build sequential streaks to escalate your payout multiplier!',
    category: 'CARDS',
    iconName: 'ArrowUpDown',
    thumbnail: 'https://images.unsplash.com/photo-1541278107931-e006523892df?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 3000,
    maxMultiplier: '50.00x',
    configuredRtp: 98.00,
    houseEdge: '2.00%',
    minAllowedRtp: 94.0,
    maxAllowedRtp: 99.0,
    sortOrder: 9,
    featured: false,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'A base card is dealt face up from a standard 52-card deck',
      'Guess whether the subsequent card will have a Higher or Lower rank (Aces can be low or high)',
      'Additional options include Same Rank, Red/Black, or Specific Suit side bets',
      'Each correct choice compounds your streak multiplier; cash out at any time to collect'
    ],
    history: 'A traditional British and American card game popularized on television game shows like Card Sharks.',
    strategy: 'Predict "Higher" when facing cards 2-6, and "Lower" on 9-K. Cash out after 3-4 consecutive wins to lock profits.',
    version: 1
  },
  {
    id: 10,
    slug: 'baccarat',
    name: 'Baccarat',
    displayName: 'Punto Banco Baccarat',
    description: 'Bet on Player, Banker, or Tie in this classic table game. Natural 8s and 9s, tableau drawing rules, and 0.95x Banker commission.',
    category: 'TABLE',
    iconName: 'Crown',
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 5000,
    maxMultiplier: '8.00x (Tie pays 8:1)',
    configuredRtp: 98.94,
    houseEdge: '1.06%',
    minAllowedRtp: 95.0,
    maxAllowedRtp: 99.2,
    sortOrder: 10,
    featured: false,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Place bets on Player, Banker, or Tie before the deal',
      'Two cards are dealt to both Player and Banker hands; card totals modulo 10 (tens and face cards = 0)',
      'Hand closest to 9 wins; standard third-card drawing rules apply automatically',
      'Banker win pays 1:1 with 5% house commission (0.95x net), Player pays 1:1, Tie pays 8:1'
    ],
    history: 'Originating in 15th-century Italy and favored by French nobility and high rollers across Macau and Las Vegas.',
    strategy: 'The Banker bet holds the mathematically lowest house edge (1.06%). Avoid Tie bets due to high variance.',
    version: 1
  },
  {
    id: 11,
    slug: 'dragontiger',
    name: 'Dragon Tiger',
    displayName: 'Dragon Tiger Duel',
    description: 'Rapid two-card showdown. Bet on Dragon or Tiger; the single card with the higher value wins instantly!',
    category: 'CARDS',
    iconName: 'Flame',
    thumbnail: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 5000,
    maxMultiplier: '8.00x (Tie)',
    configuredRtp: 96.27,
    houseEdge: '3.73%',
    minAllowedRtp: 92.0,
    maxAllowedRtp: 98.0,
    sortOrder: 11,
    featured: false,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Wager on Dragon, Tiger, or Tie',
      'One card is dealt to Dragon and one to Tiger (King is highest 13, Ace is lowest 1)',
      'The position with the higher card wins 1:1 payout',
      'In the event of equal rank, Tie bet pays 8:1 while main bets return 50%'
    ],
    history: 'Originated in Cambodia and widely recognized as the fastest, simplest live table game in Asian gaming halls.',
    strategy: 'Alternate between Dragon and Tiger; strictly adhere to even-money wagers for long-term balance stability.',
    version: 1
  },
  {
    id: 12,
    slug: 'keno',
    name: 'Keno',
    displayName: 'Cyber Keno 80',
    description: 'Pick 1 to 10 lucky numbers on the 80-ball matrix. 20 winning balls are drawn in a neon hopper with tiered match multipliers.',
    category: 'CASUAL',
    iconName: 'Grid',
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 1000,
    maxMultiplier: '1000.00x (10/10 Match)',
    configuredRtp: 96.00,
    houseEdge: '4.00%',
    minAllowedRtp: 92.0,
    maxAllowedRtp: 98.0,
    sortOrder: 12,
    featured: false,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Select between 1 and 10 numbers from the 1-80 board (or use Quick Pick)',
      'Press Play to initiate the 20-number animated ball hopper draw',
      'Hits highlight with neon accents; payouts scale based on how many chosen numbers match the drawn set',
      'Matching 10/10 unlocks the top 1000x jackpot payout'
    ],
    history: 'Keno dates back over 2,000 years to the Han Dynasty in ancient China and helped finance the Great Wall.',
    strategy: 'Selecting 4 to 7 numbers provides optimal probability of hitting rewarding mid-tier multipliers.',
    version: 1
  },
  {
    id: 13,
    slug: 'sicbo',
    name: 'Sic Bo',
    displayName: 'Sic Bo Ancient Dice',
    description: 'Three dice shaken in a glass dome. Bet on Small (4-10), Big (11-17), Specific Triples, Doubles, and Total Sums.',
    category: 'DICE',
    iconName: 'Dice3',
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 5000,
    maxMultiplier: '180.00x (Specific Triple)',
    configuredRtp: 97.22,
    houseEdge: '2.78%',
    minAllowedRtp: 93.0,
    maxAllowedRtp: 98.5,
    sortOrder: 13,
    featured: false,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Three dice are tumbled inside the shaker cage',
      'Small bets win on totals 4-10; Big bets win on totals 11-17 (triples lose on Big/Small)',
      'Bet on individual dice, two-dice combinations, exact total sums (4-17), or Any/Specific Triples',
      'Specific triples (e.g. 6-6-6) award massive 180:1 returns'
    ],
    history: 'A venerable Chinese dice game known as "Dai Siu" or "Tai Sai", widely celebrated across Macau.',
    strategy: 'Small and Big bets carry a low 2.78% house edge, making them ideal core bets.',
    version: 1
  },
  {
    id: 14,
    slug: 'tower',
    name: 'Tower',
    displayName: 'Neon Tower Climb',
    description: 'Climb 9 rows of glowing platforms. Pick safe tiles on each tier to ascend higher and multiply your potential cashout.',
    category: 'CASUAL',
    iconName: 'Building2',
    thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 2000,
    maxMultiplier: '100.00x',
    configuredRtp: 98.00,
    houseEdge: '2.00%',
    minAllowedRtp: 94.0,
    maxAllowedRtp: 99.0,
    sortOrder: 14,
    featured: false,
    isNew: true,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Select difficulty mode (Easy, Medium, Hard, Extreme) which alters safe tiles per row',
      'Click one tile on row 1 to reveal a safe passage or trap',
      'Each cleared row increases your accumulated payout multiplier',
      'Cash out anytime to lock in your profit, or risk ascending all 9 rows for maximum reward'
    ],
    history: 'Modern multiplier arcade game combining risk-escalation mechanics with interactive decision trees.',
    strategy: 'Easy and Medium modes allow steady 3-5 row climbs. Set a target cashout tier before starting the climb.',
    version: 1
  },
  {
    id: 15,
    slug: 'videopoker',
    name: 'Video Poker',
    displayName: 'Jacks or Better Video Poker',
    description: 'Classic 5-card draw video poker. Hold your best cards and redraw for winning hands from Jacks or Better to Royal Flush.',
    category: 'CARDS',
    iconName: 'Gamepad2',
    thumbnail: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 1000,
    maxMultiplier: '250.00x (Royal Flush)',
    configuredRtp: 99.54,
    houseEdge: '0.46%',
    minAllowedRtp: 95.0,
    maxAllowedRtp: 99.8,
    sortOrder: 15,
    featured: false,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Receive 5 cards on initial deal',
      'Click cards to toggle HOLD status on promising combinations',
      'Press Draw to replace unheld cards from the remaining 47-card deck',
      'Final 5-card hand is evaluated: Pair of Jacks or Better (1x), Two Pair (2x), Full House (9x), Royal Flush (250x)'
    ],
    history: 'Introduced in the late 1970s by SIRCOMA (IGT) and celebrated for offering some of the highest mathematical RTPs in casinos.',
    strategy: 'Never break a made Flush or Straight; keep high pairs (J-A) over single high cards.',
    version: 1
  },
  {
    id: 16,
    slug: 'threecardpoker',
    name: 'Three Card Poker',
    displayName: '3 Card Poker & Pair Plus',
    description: 'Fast-paced poker showdown with just 3 cards. Beat the dealer with Queen-high or better, and win big on Pair Plus side bets!',
    category: 'TABLE',
    iconName: 'Layers',
    thumbnail: 'https://images.unsplash.com/photo-1541278107931-e006523892df?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 3000,
    maxMultiplier: '40.00x (Straight Flush)',
    configuredRtp: 97.99,
    houseEdge: '2.01%',
    minAllowedRtp: 93.0,
    maxAllowedRtp: 98.8,
    sortOrder: 16,
    featured: false,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Place Ante wager and optional Pair Plus side wager',
      'Receive 3 cards face up while dealer receives 3 face down',
      'Choose to Play (match Ante stake) or Fold (forfeit Ante)',
      'Dealer qualifies with Queen-high or better; Pair Plus pays independently based on your 3-card hand ranking'
    ],
    history: 'Patented in 1994 by Derek Webb to deliver fast casino poker action with substantial side bet payouts.',
    strategy: 'Standard optimal strategy: Play when holding Q-6-4 or higher; fold anything lower.',
    version: 1
  },
  {
    id: 17,
    slug: 'scratchcards',
    name: 'Scratch Cards',
    displayName: 'Neon Scratchers',
    description: 'Scratch virtual foil surfaces to reveal hidden symbols. Match 3 symbols or special bonus multipliers for instant prizes!',
    category: 'CASUAL',
    iconName: 'Sparkles',
    thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 500,
    maxMultiplier: '500.00x',
    configuredRtp: 96.50,
    houseEdge: '3.50%',
    minAllowedRtp: 92.0,
    maxAllowedRtp: 98.0,
    sortOrder: 17,
    featured: false,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Purchase your scratch ticket at your chosen stake',
      'Drag to scratch each cell individually or use "Scratch All" for instant revelation',
      'Match 3 identical symbols (e.g. 💎 Diamonds, 7️⃣ Sevens, 👑 Crowns) to win the corresponding multiplier',
      'Wild and Bonus multiplier symbols compound your final prize'
    ],
    history: 'First developed in 1974 by Scientific Games using computerized instant lottery algorithms.',
    strategy: 'Scratch cards are pure probability; choose themes that match your preferred prize structure.',
    version: 1
  },
  {
    id: 18,
    slug: 'war',
    name: 'Casino War',
    displayName: 'Casino War Clash',
    description: 'The ultimate high card duel. Match the dealer’s rank? Surrender half your bet or Go to War for a 3.8x double-down victory!',
    category: 'CARDS',
    iconName: 'ShieldAlert',
    thumbnail: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 5000,
    maxMultiplier: '3.80x (War Victory)',
    configuredRtp: 97.12,
    houseEdge: '2.88%',
    minAllowedRtp: 93.0,
    maxAllowedRtp: 98.5,
    sortOrder: 18,
    featured: false,
    isNew: false,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Place initial bet; one card dealt to player and one to dealer (Aces high)',
      'Higher card wins 1:1 payout immediately',
      'If cards tie: choose to Surrender (lose half bet) or Go to War (place equal raise stake)',
      'In War: 3 burn cards are dealt, followed by 1 card each; winning War pays out on both wagers!'
    ],
    history: 'Adapted from the timeless childhood card game into a popular fast-action casino table classic in 1993.',
    strategy: 'Always Go to War on a tie; surrendering surrenders more expected value over time.',
    version: 1
  },
  {
    id: 19,
    slug: 'tictactoe',
    name: 'Tic Tac Toe',
    displayName: 'Neon Tic-Tac-Toe',
    description: 'Match 3 in a row vs the AI on the neon 3x3 grid. Choose Easy, Medium, or Hard AI difficulty for escalated payout multipliers!',
    category: 'CASUAL',
    iconName: 'Cpu',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 1000,
    maxMultiplier: '5.00x (Hard AI Victory)',
    configuredRtp: 97.50,
    houseEdge: '2.50%',
    minAllowedRtp: 93.0,
    maxAllowedRtp: 98.5,
    sortOrder: 19,
    featured: false,
    isNew: true,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'Select your bet and difficulty (Easy: 1.5x, Medium: 3.5x, Hard: 5.0x)',
      'You play as "X", AI plays as "O"',
      'Take turns placing marks on the 3x3 grid',
      'Align 3 marks horizontally, vertically, or diagonally to win the round and collect the difficulty multiplier',
      'A tie/draw loses the wager'
    ],
    history: 'Tracing back to ancient Egyptian grid games (circa 1300 BCE) and the Roman "Terni Lapilli".',
    strategy: 'Take center or corner positions early to force the AI into defensive moves.',
    version: 1
  },
  {
    id: 20,
    slug: 'andarbahar',
    name: 'Andar Bahar',
    displayName: 'Royal Andar Bahar',
    description: 'Traditional Indian card game. Bet whether the matching Joker rank card appears on the Andar (Inside) or Bahar (Outside) pile.',
    category: 'CARDS',
    iconName: 'Sparkles',
    thumbnail: 'https://images.unsplash.com/photo-1541278107931-e006523892df?w=600&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    currency: 'USD',
    minBet: 1,
    maxBet: 5000,
    maxMultiplier: '2.00x',
    configuredRtp: 97.85,
    houseEdge: '2.15%',
    minAllowedRtp: 94.0,
    maxAllowedRtp: 99.0,
    sortOrder: 20,
    featured: true,
    isNew: true,
    soundEnabled: true,
    mobileAvailable: true,
    desktopAvailable: true,
    rules: [
      'A single Joker card is dealt in the center of the table',
      'Cards are dealt alternately to the Andar (Inside) and Bahar (Outside) piles',
      'Bet on whether the matching Joker rank card will land on Andar (1.9x) or Bahar (2.0x)',
      'Fast-paced traditional gameplay with instant resolution'
    ],
    history: 'A centuries-old traditional card game originating in Bangalore, India, widely played during festivals and online gaming platforms.',
    strategy: 'Analyze alternating pile trends and choose Andar or Bahar based on risk preference.',
    version: 1
  }
];

export function getGameDefinition(slugOrId: string | number): GameDefinition | undefined {
  return GAME_REGISTRY.find(
    g => g.slug.toLowerCase() === String(slugOrId).toLowerCase() || g.id === Number(slugOrId)
  );
}
